#!/usr/bin/env zsh

if [[ ! -o interactive ]]; then
    return
fi

compctl -K _yammit yammit

_yammit() {
  local words
  read -cA words # read the entire command line as an array of words called "words"

  shift -p words # discard the last piece (either blank or a partial string)
  reply=($($words --completion))
}
