#!/bin/sh

die() {
  >&2 echo $*
  exit 111
}

source ~/.yammit

usage() {
  die "This is a placeholder for usage"
}

yammit_call() {
  base_url=http://$YAMMIT_RECEIVER_HOST/YamahaExtendedControl/v1
  curl --silent "$base_url/$1" | jq .
}

action=$1; shift

case "$action" in
  getFeatures)
    yammit_call "system/getFeatures"
    ;;
  getNetworkStatus)
    yammit_call "system/getNetworkStatus"
    ;;
  getStatus)
    [[ -z "$1" ]] && usage
    if [ "$1" = "--completion" ]; then
      printf "main\nzone2\nzone3\nzone4\n"
    else
      zone=$1; shift
      yammit_call "${zone}/getStatus"
    fi
    ;;
  setInput)
    [[ -z "$1" ]] && usage
    if [ "$1" = "--completion" ]; then
      printf "main\nzone2\nzone3\nzone4\n"
    elif [ "$2" = "--completion" ]; then
      $0 getFeatures | jq -r '.system | .input_list[] | .id'
    else
      zone=$1; shift
      input=$1; shift
      # TK optional "mode" param
      yammit_call "${zone}/setInput?input=${input}"
    fi
    ;;
  setPower)
    [[ -z "$1" ]] && usage
    if [ "$1" = "--completion" ]; then
      printf "main\nzone2\nzone3\nzone4\n"
    elif [ "$2" = "--completion" ]; then
      printf "on\nstandby\ntoggle\n"
    else
      zone=$1; shift
      power=$1; shift
      yammit_call "${zone}/setPower?power=${power}"
    fi
    ;;
  *)
    usage
    ;;
esac
