#!/bin/sh

die() {
  >&2 echo $*
  exit 111
}

source ~/.config/yammit/env

usage() {
  die "This is a placeholder for usage"
}

yammit_call() {
  base_url=http://$YAMMIT_RECEIVER_HOST/YamahaExtendedControl/v1
  curl --silent "$base_url/$1" | jq .
}

yammit_zones() {
  $0 getFeatures | jq -r '.zone[] | .id'
}

action=$1; shift

case "$action" in
  getDeviceInfo)
    if [ "$1" != "--completion" ]; then
      yammit_call "system/getDeviceInfo"
    fi
    ;;
  getFeatures)
    if [ "$1" != "--completion" ]; then
      yammit_call "system/getFeatures"
    fi
    ;;
  getMacAddressFilter)
    if [ "$1" != "--completion" ]; then
      yammit_call "system/getMacAddressFilter"
    fi
    ;;
  getNetworkStatus)
    if [ "$1" != "--completion" ]; then
      yammit_call "system/getNetworkStatus"
    fi
    ;;
  getPlayInfo)
    if [ "$1" != "--completion" ]; then
      yammit_call "netusb/getPlayInfo"
    fi
    ;;
  getRecentInfo)
    if [ "$1" != "--completion" ]; then
      yammit_call "netusb/getRecentInfo"
    fi
    ;;
  getStatus)
    [[ -z "$1" ]] && usage
    if [ "$1" = "--completion" ]; then
      yammit_zones
    else
      zone=$1; shift
      yammit_call "${zone}/getStatus"
    fi
    ;;
  setInput)
    [[ -z "$1" ]] && usage
    if [ "$1" = "--completion" ]; then
      yammit_zones
    elif [ "$2" = "--completion" ]; then
      $0 getFeatures | jq -r '.system | .input_list[] | .id'
    else
      zone=$1; shift
      input=$1; shift
      # TK optional "mode" param
      yammit_call "${zone}/setInput?input=${input}"
    fi
    ;;
  setPlayback)
    if [ "$1" = "--completion" ]; then
      printf "play\nstop\npause\nplay_pause\nprevious\nnext\nfast_reverse_start\nfast_reverse_end\nfast_forward_start\nfast_forward_end\n"
    else
      playback=$1; shift
      yammit_call "netusb/setPlayback?playback=${playback}"
    fi
    ;;
  setPower)
    [[ -z "$1" ]] && usage
    if [ "$1" = "--completion" ]; then
      yammit_zones
    elif [ "$2" = "--completion" ]; then
      printf "on\nstandby\ntoggle\n"
    else
      zone=$1; shift
      power=$1; shift
      yammit_call "${zone}/setPower?power=${power}"
    fi
    ;;
  setVolume)
    [[ -z "$1" ]] && usage
    if [ "$1" = "--completion" ]; then
      yammit_zones
    elif [ "$2" = "--completion" ]; then
      printf "up\ndown\n" # TK also accept integers in range_step
    else
      zone=$1; shift
      volume=$1; shift
      yammit_call "${zone}/setVolume?volume=${volume}"
    fi
    ;;
  *)
    usage
    ;;
esac
